### PR TITLE
Move Python package installation to conda where possible

### PR DESCRIPTION
**Pull request by nathanlcarlson**
The packages remaining in requirements.txt were not found in conda.
A good next step to take would be to determine which packages are
still being used and clean up those that are not. This could be done
in this pull request or a separate issue could be open. It may be 
better to do the cleanup nearer the end of development.

### CODE REVIEW

**Comment by nathanlcarlson** [comment]
This commit is to resolve #466

**Comment by nathanlcarlson** [comment]
@sashakames William mentioned there is a Python package, he thought it may be sqlalchemy, that requires a specific version. Do you happen to know which package?

**Comment by sashakames** [comment]
We fixed the SQLalchemy version issue.  However, cfpython we were installing at 2.2.1

**Comment by nathanlcarlson** [comment]
@sashakames I can't find any references to cfpython (or cf-python) in the current version of the installer. Should it still be a part of the installer?

**Comment by William-Hill** [comment]
@nathanlcarlson looks like cdfcim might have to be upgraded to a newer version according to this: https://github.com/ESGF/esgf-installer/issues/468#issuecomment-415166835

**Comment by nathanlcarlson** [comment]
@William-Hill I see. Should we get the latest?
https://pypi.org/project/cdf2cim/#history

**Comment by William-Hill** [comment]
cdf2cim==0.2.3.0
cf-python==2.2.1
These are currently in esg-node on the master branch for 2.x.  Let's go with those

**Comment by nathanlcarlson** [comment]
Was just about to post nearly the exact same thing.

**Comment by nathanlcarlson** [comment]
Pip's install doc for future reference:

> Once pip has the set of requirements to satisfy, it chooses which version of each requirement to install using the simple rule that the latest version that satisfies the given constraints will be installed

**Comment by nathanlcarlson** [comment]
from pip freeze with python_devel
cdf2cim==0.2.3.0
cf-python==2.2.7

**Comment by nathanlcarlson** [comment]
@William-Hill This is what is going to tell you that I forgot. This is no longer a work in progress and is ready for testing.

**Pull request merged**
