### PR TITLE
Static files

### PR DESCRIPTION
**Pull request by William-Hill**
This PR removes any network calls to the distribution mirror for static files such as XML files and shell scripts.  Downloading jar/war files is still done via the distribution mirror

### CODE REVIEW

**Comment by William-Hill** [comment]
@nathanlcarlson This is now ready for review

**Comment by nathanlcarlson** [comment]
@William-Hill What are `esgf-migrate-user` and `esgf-policy-check`?

**Comment by William-Hill** [comment]
@nathanlcarlson Those file are more than likely deprecated, but I added them for completeness initially.  I have now removed them

**Comment by nathanlcarlson** [comment]
@William-Hill As I mention in #655, @sashakames suggested that esgf-ca-bundle.crt and esg-truststore.ts should be fetched from the mirror. I will wait for him to weigh in on which direction we should take.

**Comment by nathanlcarlson** [comment]
@William-Hill  So we will merge this in, but first it looks like there are some merge conflicts to resolve. It is probably best if you do that, but I can do it if you would like.

**Comment by William-Hill** [comment]
@nathanlcarlson Fixed merge conflicts

**Pull request merged**
