### PR TITLE
604

### PR DESCRIPTION
**Pull request by William-Hill**
May need more changes to the Ansible config.  It appears that using the virtualenv in the Ansible playbook causing a conflict

### CODE REVIEW

**Comment by William-Hill** [comment]
Had to make changes to the playbook (https://github.com/ESGF/esgf-slcs-server-playbook) and the slcs repo (https://github.com/ESGF/esgf-slcs-server) so I will be making PRs for those as well

**Comment by nathanlcarlson** [comment]
@William-Hill I am looking to merge this in, but am waiting for the PR's on the other repositories to be merged in.

**Comment by William-Hill** [comment]
@nathanlcarlson This should be fine to go ahead and merge because it is referencing a 3.0 branch on the playbook repo.  The PR for the playbook repo probably shouldn't be merged until we release 3.0 to avoid potentially breaking 2.x installs.

**Comment by nathanlcarlson** [comment]
Gotcha, will do.

**Pull request merged**
