### PR TITLE
install myproxy-libs at same time as myproxy

### PR DESCRIPTION
**Pull request by alaniwi**
Per issue 161

### CODE REVIEW

**Comment by pchengi** [comment]
@alaniwi , I think what needs to be done is to leave out myproxy also, and NOT to add myproxy-libs, in addition to myproxy. I'm checking on this right now.

**Comment by pchengi** [comment]
I tested by removing myproxy completely from the list of packages installed using yum and it works as expected. Note that the esg-node script is fetched from the distribution servers and not from git. I have now modified the esg-node script for 2.3, on the distribution mirrors, removing the myproxy line. This stops esg-node from failing during the globus installation. If you for some reason need the other myproxy, by all means attempt by installing all the globus packages by hand, prior to doing an esgf installation.  Your mileage may vary, though. For 2.4, which is in devel, myproxy has been removed from the yum list.

**Comment by pchengi** [comment]
I just performed a clean installation of 2.3.8 master, without any install-time failures. The log is available here:
https://raw.githubusercontent.com/snic-nsc/esgf-install-logs/master/2.3/v2.3.8-master-release/installation.log-2017-01-05_12-14-44.txt

**Comment by alaniwi** [comment]
The failure I had was at publication time, not at installation time. (Specifically, it was when trying to run `myproxy-logon` manually before running the publisher.) The `yum install myproxy` without myproxy-libs was breaking an otherwise working myproxy-logon on a system which had earlier versions of both myproxy and myproxy-libs pre-installed.
- If esg-node _does not_ install myproxy, then this will avoid the breakage I described, but also it will obviously fail to provide a working myproxy-logon on a system that doesn't already have it, leaving more manual steps for node admins.
- If esg-node _does_ install myproxy, then until Globus re-add the dependency, it needs to install myproxy-libs also, in order to reduce risk of inconsistent versions. (I see at least that they've assigned that ticket now - https://github.com/globus/globus-toolkit/issues/85.)

(I take the point that merging into git would not *immediately* affect `esg-node` fetched from the distribution servers, but presuambly it would do in due course.)

**Pull request closed without merging**
